[build]
builder = "nixpacks"

[build.nixpacks]
buildCmd = "npx prisma generate && npx tsc && cp -r public dist/"

[deploy]
startCommand = "npx prisma generate && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
