import { EnergyType } from './types.js';
import type { MicroAction, TimeOfDay } from './types.js';
import { ENERGY_FACTS } from './energy-facts.js';

const MICRO_ACTIONS = new Map<EnergyType, MicroAction[]>([
  [EnergyType.physical, [
    // 10 physical actions — micro first, then regular, then deep
    { id: 'pushups-10', name: '10 отжиманий', description: 'Упади и сделай 10. От стены, если тяжело. Кровь побежит через 30 секунд.', energyType: EnergyType.physical, duration: 2, timeOfDay: ['anytime'], context: ['home', 'work'], intensity: 'micro', science: 'Кровоток ↑ → эндорфины → активация симпатики', canBeHabit: true, habitSuggestion: 'После утреннего кофе — 10 отжиманий' },
    { id: 'stairs-3', name: '3 пролёта лестницы быстро', description: 'Найди лестницу и вверх. Быстро. Одышка = сигнал что работает.', energyType: EnergyType.physical, duration: 2, timeOfDay: ['morning', 'afternoon'], context: ['work', 'home'], intensity: 'micro', science: 'VO2 ↑; 1-2 мин vigorous = −48% кардио-риска', canBeHabit: true, habitSuggestion: 'Перед обедом — 3 пролёта лестницы' },
    { id: 'water-breathe', name: 'Стакан воды + 10 глубоких вдохов', description: 'Прямо сейчас. Вода + кислород — два базовых ресурса тела.', energyType: EnergyType.physical, duration: 2, timeOfDay: ['morning'], context: ['anywhere'], intensity: 'micro', science: '−1-2% воды = −когниция; глубокие вдохи оксигенируют', canBeHabit: true, habitSuggestion: 'Сразу после пробуждения — стакан воды' },
    { id: 'cold-face', name: 'Холодная вода на лицо', description: '15 секунд холодной воды на лицо. Мгновенное пробуждение.', energyType: EnergyType.physical, duration: 1, timeOfDay: ['afternoon'], context: ['home', 'work'], intensity: 'micro', science: 'Dive reflex: вагус → пульс ↓ → мгновенная бодрость', crossTypeBonus: [EnergyType.emotional], canBeHabit: false },
    { id: 'chair-squats-5', name: '5 приседаний у стула + 5 подъёмов на носки', description: 'Встал, 5 приседаний, 5 подъёмов на носки. Сел обратно. 60 секунд.', energyType: EnergyType.physical, duration: 2, timeOfDay: ['afternoon'], context: ['work'], intensity: 'micro', science: 'Exercise snack: глюкоза ↓, сидячий вред ↓', canBeHabit: true, habitSuggestion: 'Между встречами — 5 приседаний' },
    { id: 'dance-1-song', name: 'Потанцуй под 1 песню', description: 'Включи любимый трек и двигайся 3 минуты. Дофамин + кардио.', energyType: EnergyType.physical, duration: 5, timeOfDay: ['morning', 'evening'], context: ['home'], intensity: 'regular', science: 'Кардио + дофамин (музыка) + эмоц. подъём', crossTypeBonus: [EnergyType.emotional], canBeHabit: true, habitSuggestion: 'Утром после душа — 1 песня с танцем' },
    { id: 'stretch-5min', name: '5-минутная растяжка', description: 'Шея, плечи, бёдра. Медленно, с дыханием. Тело скажет спасибо.', energyType: EnergyType.physical, duration: 5, timeOfDay: ['afternoon', 'evening'], context: ['home', 'work'], intensity: 'regular', science: 'Снимает мышечное напряжение, парасимпатика через медленное движение', canBeHabit: true, habitSuggestion: 'В 15:00 — 5 минут растяжки' },
    { id: 'sunlight-10min', name: 'Утренний свет 10 минут', description: 'Выйди на свет в первый час после пробуждения. Без очков. Не в телефон.', energyType: EnergyType.physical, duration: 15, timeOfDay: ['morning'], context: ['outside'], intensity: 'regular', science: 'Циркадный ресет: серотонин ↑, мелатонин подготовка, кортизол awakening', crossTypeBonus: [EnergyType.mental], canBeHabit: true, habitSuggestion: 'Сразу после пробуждения — на свет' },
    { id: 'walk-15min', name: 'Прогулка 15 минут', description: 'Выйди и иди. Без цели, без телефона. 15 минут — и кортизол тает.', energyType: EnergyType.physical, duration: 15, timeOfDay: ['anytime'], context: ['outside'], intensity: 'regular', science: '−21% кортизола/час; BDNF ↑; метаболизм глюкозы ↑', crossTypeBonus: [EnergyType.mental, EnergyType.emotional], canBeHabit: true, habitSuggestion: 'После обеда — 15 минут на улице' },
    { id: 'power-nap', name: 'Power nap 15 минут', description: 'Поставь таймер на 15 минут. Ляг. Закрой глаза. Даже если не уснёшь — мозг отдохнёт.', energyType: EnergyType.physical, duration: 15, timeOfDay: ['afternoon'], context: ['home', 'work'], intensity: 'regular', science: 'NASA: +54% alertness, +34% performance; ATP восполнение', crossTypeBonus: [EnergyType.mental], canBeHabit: true, habitSuggestion: 'В 13:00-14:00 — 15 минут power nap' },
  ]],

  [EnergyType.mental, [
    { id: 'look-at-nature', name: 'Посмотри на дерево 2 минуты', description: 'Найди дерево или растение за окном. Смотри 2 минуты. Ничего не делай.', energyType: EnergyType.mental, duration: 2, timeOfDay: ['anytime'], context: ['work', 'home'], intensity: 'micro', science: 'Attention Restoration Theory: мягкий фокус восстанавливает направленное внимание', canBeHabit: false },
    { id: 'breathing-478', name: 'Дыхание 4-7-8, 3 цикла', description: 'Вдох 4 сек, задержка 7, выдох 8. Три раза. Мозг переключится.', energyType: EnergyType.mental, duration: 2, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Активация префронтальной коры, снижение DMN-шума', crossTypeBonus: [EnergyType.emotional], canBeHabit: true, habitSuggestion: 'Перед каждой важной задачей — 3 цикла 4-7-8' },
    { id: 'write-3-priorities', name: 'Выпиши 3 приоритета на 2 часа', description: 'Бумага или заметка. 3 вещи на ближайшие 2 часа. Остальное — бонус.', energyType: EnergyType.mental, duration: 2, timeOfDay: ['morning', 'afternoon'], context: ['work'], intensity: 'micro', science: 'Разгрузка рабочей памяти (эффект Зейгарник), фокус префронтальной коры', canBeHabit: true, habitSuggestion: 'В начале рабочего дня — 3 приоритета' },
    { id: 'walk-no-phone', name: 'Прогулка 5 мин без телефона', description: 'Оставь телефон. Выйди. 5 минут. Глаза на горизонт.', energyType: EnergyType.mental, duration: 5, timeOfDay: ['afternoon'], context: ['outside'], intensity: 'regular', science: 'Природа + движение: двойное восстановление рабочей памяти', crossTypeBonus: [EnergyType.physical], canBeHabit: true, habitSuggestion: 'После обеда — 5 минут без телефона на улице' },
    { id: 'instrumental-music', name: 'Инструментальная музыка 5 мин', description: 'Надень наушники. Без слов — только инструменты. Закрой глаза.', energyType: EnergyType.mental, duration: 5, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'regular', science: 'Снижает когнитивную интерференцию; бинауральные ритмы ↑ альфа-волны', canBeHabit: false },
    { id: 'puzzle-1-round', name: '1 раунд словесной игры', description: 'Wordle, кроссворд, судоку — 5 минут. Мозг переключится на другую задачу.', energyType: EnergyType.mental, duration: 5, timeOfDay: ['afternoon'], context: ['anywhere'], intensity: 'regular', science: 'Когнитивное переключение восстанавливает утомлённые attention networks', canBeHabit: false },
    { id: 'teach-1-thing', name: 'Расскажи кому-то 1 вещь', description: 'Что узнал сегодня? Расскажи коллеге или другу. 5 минут.', energyType: EnergyType.mental, duration: 5, timeOfDay: ['evening'], context: ['work', 'home'], intensity: 'regular', science: 'Protégé effect: обучение консолидирует знания, перезаряжает ментальные модели', canBeHabit: true, habitSuggestion: 'Вечером — расскажи 1 инсайт дня' },
    { id: 'nature-20min', name: '20 минут в парке/зелени', description: 'Парк, сквер, сад — 20 минут. Без телефона. Просто будь.', energyType: EnergyType.mental, duration: 15, timeOfDay: ['afternoon'], context: ['outside'], intensity: 'regular', science: '−21.3% кортизола/час (Frontiers 2019); восстановление направленного внимания', crossTypeBonus: [EnergyType.physical, EnergyType.emotional], canBeHabit: true, habitSuggestion: 'В обед — 20 минут в парке' },
    { id: 'pomodoro-25', name: '25 минут глубокой работы', description: 'Телефон в режим полёта. 25 минут одной задачи. Потом перерыв.', energyType: EnergyType.mental, duration: 30, timeOfDay: ['morning'], context: ['work'], intensity: 'deep', science: 'Снижает attention residue; deep work восстанавливает чувство компетентности', canBeHabit: true, habitSuggestion: 'Первый час работы — 25 мин deep work без телефона' },
    { id: 'digital-sunset', name: 'Без экранов 30 мин перед сном', description: 'За полчаса до сна — убери все экраны. Книга, разговор, тишина.', energyType: EnergyType.mental, duration: 30, timeOfDay: ['evening'], context: ['home'], intensity: 'deep', science: 'Защита мелатонина, снижение когнитивного возбуждения, качество сна ↑', canBeHabit: true, habitSuggestion: 'В 22:00 — убрать все экраны' },
  ]],

  [EnergyType.emotional, [
    { id: 'physiological-sigh', name: 'Двойной вдох + длинный выдох, 3 раза', description: 'Два коротких вдоха носом, один длинный выдох ртом. 3 раза. 30 секунд.', energyType: EnergyType.emotional, duration: 1, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Stanford: самый быстрый real-time сброс стресса; вагус → парасимпатика', crossTypeBonus: [EnergyType.physical], canBeHabit: true, habitSuggestion: 'При любом стрессе — двойной вдох' },
    { id: 'name-emotion', name: 'Назови эмоцию вслух', description: '"Я замечаю, что сейчас чувствую ___". Скажи вслух или напиши.', energyType: EnergyType.emotional, duration: 1, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Affect labeling: −50% активности миндалины (Lieberman, UCLA)', canBeHabit: false },
    { id: 'box-breathing', name: 'Box breathing 4-4-4-4, 5 раз', description: 'Вдох 4, задержка 4, выдох 4, задержка 4. Пять циклов. Две минуты.', energyType: EnergyType.emotional, duration: 2, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Протокол Navy SEALs; парасимпатическая активация', canBeHabit: true, habitSuggestion: 'Перед сложным разговором — box breathing' },
    { id: 'text-close-person', name: 'Напиши близкому что-то настоящее', description: 'Не "как дела". Что-то настоящее. "Думаю о тебе" или "спасибо за...".', energyType: EnergyType.emotional, duration: 2, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Социальная связь — сильнейший предиктор счастья и долголетия (Harvard)', canBeHabit: true, habitSuggestion: 'Каждый вечер — одно настоящее сообщение' },
    { id: 'gratitude-3', name: '3 благодарности с деталями', description: 'Запиши 3 конкретные вещи, за которые благодарен. С деталями — не "семья", а "как дочка засмеялась за завтраком".', energyType: EnergyType.emotional, duration: 5, timeOfDay: ['morning', 'evening'], context: ['home', 'work'], intensity: 'regular', science: 'Активация reward circuits, серотонин ↑, дофамин ↑, качество сна ↑', canBeHabit: true, habitSuggestion: 'Перед сном — 3 благодарности' },
    { id: 'body-scan-5min', name: 'Сканирование тела 5 минут', description: 'Закрой глаза. Медленно пройдись вниманием от макушки до пяток. Где зажим? Отпусти.', energyType: EnergyType.emotional, duration: 5, timeOfDay: ['afternoon', 'evening'], context: ['home', 'work'], intensity: 'regular', science: 'Reconnects mind-body; снимает соматические паттерны стресса', canBeHabit: true, habitSuggestion: 'В 15:00 — 5 минут body scan' },
    { id: 'laugh-5min', name: 'Посмотри/прочитай что-то смешное', description: '5 минут чистого юмора. Мемы, стендап, смешное видео. Без вины.', energyType: EnergyType.emotional, duration: 5, timeOfDay: ['afternoon'], context: ['anywhere'], intensity: 'regular', science: 'Смех: −39% кортизола, ↑ эндорфины, ↑ NK-клетки иммунитета', canBeHabit: false },
    { id: 'brain-dump', name: 'Brain dump — выгрузи всё на бумагу', description: 'Всё что тревожит — на бумагу. Без фильтра, без структуры. 5 минут.', energyType: EnergyType.emotional, duration: 5, timeOfDay: ['evening'], context: ['home', 'work'], intensity: 'regular', science: 'Экстернализация руминации, разгрузка рабочей памяти от эмоц. процессинга', crossTypeBonus: [EnergyType.mental], canBeHabit: true, habitSuggestion: 'Перед сном — brain dump 5 минут' },
    { id: 'hug-20sec', name: 'Обними кого-то на 20 секунд', description: 'Не быстрое касание — полноценные 20 секунд. Тело начнёт расслабляться.', energyType: EnergyType.emotional, duration: 1, timeOfDay: ['morning', 'evening'], context: ['home'], intensity: 'micro', science: 'Окситоцин ↑, кортизол ↓, давление ↓', canBeHabit: true, habitSuggestion: 'Утром и вечером — обнять близкого' },
    { id: 'cold-face-emotional', name: 'Холодная вода на лицо и запястья', description: 'Когда эмоции зашкаливают — 15 секунд холодной воды. Мгновенный ресет.', energyType: EnergyType.emotional, duration: 1, timeOfDay: ['anytime'], context: ['home', 'work'], intensity: 'micro', science: 'Mammalian dive reflex: пульс ↓, нервная система ресет за 15 сек', crossTypeBonus: [EnergyType.physical], canBeHabit: false },
  ]],

  [EnergyType.spiritual, [
    { id: 'why-matters', name: '"Зачем это важно?" — 1 предложение', description: 'То, чем сейчас занят — зачем? Напиши одно предложение, связывающее с ценностями.', energyType: EnergyType.spiritual, duration: 2, timeOfDay: ['morning'], context: ['work'], intensity: 'micro', science: 'Purpose priming: вентромедиальная ПФК ↑, persistence ↑', canBeHabit: true, habitSuggestion: 'В начале дня — "зачем я это делаю?"' },
    { id: 'look-at-sky', name: 'Посмотри на небо 2 минуты', description: 'Остановись. Подними глаза. Небо, облака, звёзды. 2 минуты тишины.', energyType: EnergyType.spiritual, duration: 2, timeOfDay: ['anytime'], context: ['outside'], intensity: 'micro', science: 'Awe experience: ↓ self-focus, ↑ чувство связи с чем-то большим', canBeHabit: false },
    { id: 'peak-memory', name: 'Вспомни пиковый момент жизни', description: 'Закрой глаза. Вспомни момент когда ты чувствовал "вот ради этого". 2 минуты.', energyType: EnergyType.spiritual, duration: 2, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'micro', science: 'Автобиографическая память о смысле активирует reward + identity circuits', canBeHabit: false },
    { id: 'silent-sitting-5min', name: '5 минут тишины', description: 'Сядь. Закрой глаза. Дыши. Ничего не делай. 5 минут.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['morning', 'evening'], context: ['home', 'work'], intensity: 'regular', science: 'Медитация: ↑ ПФК активация, ↓ DMN блуждание', crossTypeBonus: [EnergyType.mental], canBeHabit: true, habitSuggestion: 'Утром после пробуждения — 5 минут тишины' },
    { id: 'read-1-page', name: '1 страница глубокой книги', description: 'Философия, поэзия, мудрость. Одна страница. Не скроллинг — книга.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['morning', 'evening'], context: ['home'], intensity: 'regular', science: 'Engagement с трансцендентными идеями активирует meaning-making circuits', canBeHabit: true, habitSuggestion: 'Перед сном — 1 страница глубокой книги' },
    { id: 'help-someone', name: 'Помоги кому-то в малом', description: 'Сегодня — одна маленькая помощь. Коллеге, незнакомцу, близкому.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['anytime'], context: ['work', 'home'], intensity: 'regular', science: 'Helper\'s high: эндорфины ↑, чувство значимости ↑', crossTypeBonus: [EnergyType.emotional], canBeHabit: true, habitSuggestion: 'Каждый день — 1 маленькая помощь' },
    { id: 'frisson-music', name: 'Музыка, от которой мурашки', description: 'Та самая музыка. Наушники. Громко. 5 минут чистого кайфа.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['anytime'], context: ['anywhere'], intensity: 'regular', science: 'Frisson: дофамин в anticipation circuits; трансцендентный эмоциональный опыт', crossTypeBonus: [EnergyType.emotional], canBeHabit: false },
    { id: 'appreciation-letter', name: 'Напиши 3 предложения благодарности кому-то', description: 'Не обязательно отправлять. Просто напиши кому и за что. 5 минут.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['evening'], context: ['home', 'work'], intensity: 'regular', science: 'Активация gratitude + empathy networks; укрепление социальных связей', crossTypeBonus: [EnergyType.emotional], canBeHabit: true, habitSuggestion: 'Вечером — 3 предложения благодарности' },
    { id: 'walk-what-matters', name: 'Прогулка с вопросом "что сейчас важно?"', description: '10 минут. Иди и думай об одном: что сейчас по-настоящему важно?', energyType: EnergyType.spiritual, duration: 15, timeOfDay: ['morning', 'evening'], context: ['outside'], intensity: 'regular', science: 'Walking meditation + экзистенциальная рефлексия: движение + смысл', crossTypeBonus: [EnergyType.physical, EnergyType.mental], canBeHabit: true, habitSuggestion: 'Утром — 10 мин прогулка с вопросом' },
    { id: 'gratitude-learned', name: '"Чему я благодарен за эту неделю?"', description: 'Раз в неделю. Что узнал, чему научился, что получил. Напиши.', energyType: EnergyType.spiritual, duration: 5, timeOfDay: ['evening'], context: ['home'], intensity: 'regular', science: 'Gratitude + growth reflection; reinforces learning identity', canBeHabit: true, habitSuggestion: 'В воскресенье вечером — благодарность за неделю' },
  ]],
]);

export function getMicroActions(
  type: EnergyType,
  options?: { timeOfDay?: TimeOfDay },
): MicroAction[] {
  const actions = MICRO_ACTIONS.get(type) ?? [];
  if (!options?.timeOfDay) return actions;
  return actions.filter(
    a => a.timeOfDay.includes(options.timeOfDay!) || a.timeOfDay.includes('anytime'),
  );
}

export function getEnergyFacts(category?: 'low' | 'high') {
  if (!category) return ENERGY_FACTS;
  return ENERGY_FACTS.filter(f => f.category === category);
}
